steps:
  - name: eclipse-temurin:17
    id: test
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew check

  - name: "us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/skaffold:latest"
    id: build-event-arc-listener-image
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew jibDockerBuild --image=us-docker.pkg.dev/$PROJECT_ID/docker-repo/cloudbuild-eventarc-sample:$SHORT_SHA -Djib.to.tags="latest"


images:
  - us-docker.pkg.dev/$PROJECT_ID/docker-repo/cloudbuild-eventarc-sample:$SHORT_SHA
  - us-docker.pkg.dev/$PROJECT_ID/docker-repo/cloudbuild-eventarc-sample:latest
options:
  requestedVerifyOption: VERIFIED
